

POST http://localhost:3004/user/signUp
Content-Type: application/json

{
    "name":"vaibhav",
    "email":"viranshk7@gmail.com",
    "password":"1234567",
    "role":"Admin",
    "phoneNumber":"8930485009"
}

###
POST http://localhost:3004/user/generateOtp
Content-Type: application/json

{
    "email":"viranshk7@gmail.com"
}

###
POST http://localhost:3004/user/verifyOtp
Content-Type: application/json

{
    "email":"viranshk7@gmail.com",
    "otp":"318779"
}



###
POST http://localhost:3004/user/login
Content-Type: application/json

{
    "email":"viranshk7@gmail.com",
    "password":"1234567"
}


###
POST http://localhost:3004/user/login/token
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.dmlyYW5zaGs3QGdtYWlsLmNvbQ.a0zjz2vMZJDmzM_deJq7pLywteR2x_vxWAmij5Qpb8Q


###
POST http://localhost:3004/product/createProduct/647dd15e9c511f81c38e8681
Content-Type: application/json

{
    "Title":"shampoo",
    "Description":"this is good shampoo",
    "Price":200,
    "Availabilty":true,
    "Category":"Dairy"
}
###


GET http://localhost:3004/product/getAllProducts
Content-Type: application/json

