
@baseurl=https://ecommerce-production-59b6.up.railway.app/
@baseurl1=https://e-commerce-w51c.onrender.com/
@baseurl2=http://localhost:3004/

POST {{baseurl1}}user/signUp
Content-Type: application/json

{
    "name":"vaib",
    "email":"vaivt@gmail.com",
    "password":"1234567",
    "role":"Consumer",
    "phoneNumber":"8930485009"
}

###
POST {{baseurl1}}user/generateOtp
Content-Type: application/json

{
    "email":"viranshk7@gmail.com"
}
####

POST {{baseurl1}}user/verifyOtp
Content-Type: application/json

{
    "email":"viranshk7@gmail.com",
    "otp":"683075"
}



###
POST {{baseurl1}}user/login
Content-Type: application/json

{
    "email":"vaibhavtezan@gmail.com",
    "password":"1234567"
}


###
POST http://localhost:3004/user/login/token
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.dmFpYmhhdnRlemFuQGdtYWlsLmNvbQ.gPxsv52SAMuS1kB0E-qLn6szxqeEZqKR_WwiQdgRiKg



###
POST  {{baseurl1}} user/logout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.dmlyYW5zaGs3QGdtYWlsLmNvbQ.a0zjz2vMZJDmzM_deJq7pLywteR2x_vxWAmij5Qpb8Q

####
POST {{baseurl1}}product/64802883b235c90335180859/createProduct
Content-Type: application/json

{
    "Title":"cake4",
    "Description":"cake4 is more delicious ",
    "Price":2000,
    "Availability":true,
    "Category":"Dairy"
}
###


GET {{baseurl1}}product/getAllProducts
Content-Type: application/json


###

PATCH {{baseurl1}}product/64802883b235c90335180859/UpdateProduct/64802f2507d6a2961cc02192
Content-Type: application/json

{
    "Title":"cake",
    "Description":"cake is very delicious ",
    "Price":2000,
    "Availability":true,
    "Category":"Dairy"
}

###
DELETE {{baseurl1}}product/64802883b235c90335180859/deleteProduct/64802f2507d6a2961cc02192
Content-Type: application/json

###
POST {{baseurl1}}cart/647efe460d0caac65fe57f85/addTocart
Content-Type: application/json

{
    "productId":"647f18dec3d88ea6bc23b9b9",
    "quantity":4
}


###
POST {{baseurl1}}cart/64802883b235c90335180859/getCart
Content-Type: application/json



###
POST {{baseurl1}}orders/647efe460d0caac65fe57f85/placeOrder
Content-Type: application/json

{
    "Address":"gurgaon"
}
###
GET  {{baseurl1}}orders/647efe460d0caac65fe57f85/getOrder
Content-Type: application/json
