@baseurl1=https://b2cecommerce.onrender.com
@baseurl2=http://localhost:3005/
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiI2NDgwMjg4M2IyMzVjOTAzMzUxODA4NTkiLCJpYXQiOjE2ODYxNDg5MTl9.s3cA2YI29N3CAZbfcZeJCM1HFLg7zvv_w-CysjncrdA

POST http://localhost:3005/user/signUp
Content-Type: application/json

{
    "name":"kaldharm guptaa",
    "email":"kaldharmgupta@gmail.com",
    "password":"1234567",
    "role":"Consumer",
    "phoneNumber":"9315899660"
}

###
POST http://localhost:3005/user/generateOtp
Content-Type: application/json

{
    "email":"kaldharmgupta@gmail.com"
}
####

POST http://localhost:3005/user/verifyOtp
Content-Type: application/json

{
    "email":"kaldharmgupta@gmail.com",
    "otp":"430495"
}



###
POST http://localhost:3005/user/login
Content-Type: application/json

{
    "email":"kaldharmgupta@gmail.com",
    "password":"1234567"
}



###
POST  http://localhost:3005/user/changePassword
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgwYzQwY2ZlZDBjODViZTExZGYxNTQiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MTYwNzIzLCJleHAiOjE2ODYyNDcxMjN9.jdtAqPxmvORuV5dhrnQaRKbjrx_5KBECXAZq9AwNErE

{
    "oldPassword":"123456",
    "newPassword":"1234567"
}
###
POST  http://localhost:3005/user/logout
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgwYzQwY2ZlZDBjODViZTExZGYxNTQiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MTYwNzIzLCJleHAiOjE2ODYyNDcxMjN9.jdtAqPxmvORuV5dhrnQaRKbjrx_5KBECXAZq9AwNErE


####
POST http://localhost:3005/product/createproduct
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyMTE4MjQwZmFhZDY5ZmI3NjE4ODgiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjQ1ODQ1LCJleHAiOjE2ODYzMzIyNDV9.nR6eyG03-TSUOy6uKFolEP3yxShFYJu1Ojdned2yqZ8

{
    "Title":"babycare231",
    "Description":"babaycare  is more cheap product ",
    "Price":20,
    "Availability":true,
    "Category":"Electronics"
  
}


###
GET http://localhost:3005/product/getAllProducts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgxZjdmOTNiZTY0MTA5ZmZhMzdlMGEiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjM5Njk5LCJleHAiOjE2ODYzMjYwOTl9.QacAVBjgVlZV55eaQZ-ciucQRWRz3Y4YCpp5fxwzghg



###

PATCH http://localhost:3005/product/UpdateProduct
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgxZjdmOTNiZTY0MTA5ZmZhMzdlMGEiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjM5Njk5LCJleHAiOjE2ODYzMjYwOTl9.QacAVBjgVlZV55eaQZ-ciucQRWRz3Y4YCpp5fxwzghg

{
    "Productid":"648201facdb76d0224ee096a",
    "Title":"amazing cake",
    "Description":"cake is very delicious ",
    "Price":2000,
    "Availability":true,
    "Category":"Dairy"
}

###
DELETE http://localhost:3005/product/648201facdb76d0224ee096a/deleteProduct
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgxZjdmOTNiZTY0MTA5ZmZhMzdlMGEiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjM5Njk5LCJleHAiOjE2ODYzMjYwOTl9.QacAVBjgVlZV55eaQZ-ciucQRWRz3Y4YCpp5fxwzghg

{
    "ProductId":"648201facdb76d0224ee096a"
}


###
POST http://localhost:3005/cart/addTocart
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyMTE4MjQwZmFhZDY5ZmI3NjE4ODgiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjQ1ODQ1LCJleHAiOjE2ODYzMzIyNDV9.nR6eyG03-TSUOy6uKFolEP3yxShFYJu1Ojdned2yqZ8

{
    "products":[{
      "productId": "648200cf0b2e54471d7d3e98",
      "quantity": 4
     },
     {
      "productId": "648205d71470395568a57957",
      "quantity": 4
     }]
}
  
###
GET  http://localhost:3005/cart/showCart
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyMTE4MjQwZmFhZDY5ZmI3NjE4ODgiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjQ1ODQ1LCJleHAiOjE2ODYzMzIyNDV9.nR6eyG03-TSUOy6uKFolEP3yxShFYJu1Ojdned2yqZ8



###
POST http://localhost:3005/orders/placeOrder
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyMTE4MjQwZmFhZDY5ZmI3NjE4ODgiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjQ1ODQ1LCJleHAiOjE2ODYzMzIyNDV9.nR6eyG03-TSUOy6uKFolEP3yxShFYJu1Ojdned2yqZ8

{
    "Address":"gurgaon"
}


###
GET  http://localhost:3005/orders/showOrder
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDgyMTE4MjQwZmFhZDY5ZmI3NjE4ODgiLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNjg2MjQ1ODQ1LCJleHAiOjE2ODYzMzIyNDV9.nR6eyG03-TSUOy6uKFolEP3yxShFYJu1Ojdned2yqZ8
